In [1]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv("combined.csv")

In [21]:
df.head()

   Unnamed: 0                   song artist
0           0  Ahe's My Kind Of Girl   ABBA
1           1       Andante, Andante   ABBA
2           2         As Good As New   ABBA
3           3                   Bang   ABBA
4           4       Bang-A-Boomerang   ABBA

In [23]:
df[df['artist'] == 'Justin Bieber']

         Unnamed: 0                         song         artist
9994           9994      A Very Bieber Christmas  Justin Bieber
9995           9995                      All Bad  Justin Bieber
9996           9996            All I Want Is You  Justin Bieber
9997           9997       As Long As You Love Me  Justin Bieber
9998           9998                    Baby Lady  Justin Bieber
...             ...                          ...            ...
7055011     7233825  Swag So Mean Shorty O Remix  Justin Bieber
7055015     7233829      Swag So Mean GABE Remix  Justin Bieber
7055031     7233845                   Trust Demo  Justin Bieber
7055124     7233938          Thugz Mansion Cover  Justin Bieber
7088659     7267592            There She Go Demo  Justin Bieber

[461 rows x 3 columns]